config/routes.rb
Rails.application.routes.draw do

  root to: "questions#index"
  devise_for :users

  resources :questions do

  	resources :comments, only: [:create]
  	resources :answers, only: [:create]
  	resource :vote, only: [:create, :destroy]

  end

  resources :answers do

  	resources :comments
  	resource :vote, only: [:create, :destroy]

  end

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :bigint(8)        not null, primary key
#  body        :text
#  question_id :bigint(8)
#  user_id     :bigint(8)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
	
  belongs_to :question
  belongs_to :user

  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  validates :body, presence: true

  def voted_by? (user)
  	votes.exists?(user: user)  	
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :bigint(8)        not null, primary key
#  body             :text
#  user_id          :bigint(8)
#  commentable_type :string
#  commentable_id   :bigint(8)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :bigint(8)        not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint(8)
#

class Question < ApplicationRecord

	belongs_to :user
	has_many :answers
	has_many :comments, as: :commentable
	has_many :votes, as: :voteable

	validates :title, presence: true
	validates :description, presence: true

	scope :most_recent, -> { order(created_at: :desc) }

	def voted_by? (user)
		votes.exists?(user: user)
	end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id            :bigint(8)        not null, primary key
#  user_id       :bigint(8)
#  voteable_type :string
#  voteable_id   :bigint(8)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Vote < ApplicationRecord

  belongs_to :user
  belongs_to :voteable, polymorphic: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create

		question = Question.find(params[:question_id])
		question.answers.create(answers_params)

		redirect_to question

	end

	private

		def answers_params
			params.require(:answer).permit(:body).merge(user: current_user)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  private

  	def private_access
  		redirect_to new_user_session_path, notice: "You don't have access to this page" unless signed_in?
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		if params[:question_id].present?
			@question = Question.find(params[:question_id])
			@comment = @question.comments.new(comment_params)

			@comment.save

			redirect_to @question

		elsif params[:answer_id].present?
			@answer = Answer.find(params[:answer_id])
			@comment = @answer.comments.new(comment_params)

			@comment.save

			redirect_to @answer.question
		end
			
	end

	private

		def comment_params
			params.require(:comment).permit(:body).merge(user_id: current_user.id)
		end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	before_action :private_access, except: [:index, :show]

	def index

		@questions = Question.all.most_recent

		if params[:title].present?
			@questions = @questions.where("title LIKE ?", "%#{params[:title]}%")
		end

	end

	def new
		@question = Question.new
	end

	def create
		
		@question = Question.new(question_params)

		if @question.save
			redirect_to questions_path, notice: "Question asked successfully"
		else
			render :new
		end

	end

	def show
		@question = Question.find(params[:id])
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update

		question = Question.find(params[:id])

		if question.update(question_params)
			redirect_to questions_path, notice: "Question edited successfully"
		else
			render :edit
		end

	end

	def destroy

		question = Question.find(params[:id])
		question.destroy

		redirect_to questions_path, notice: "Question removed successfully"
		
	end

	private

		def question_params
			params.require(:question).permit(:title, :description).merge(user_id: current_user.id)
		end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	def create

		if params[:question_id].present?

			question = Question.find(params[:question_id])
			question.votes.create(user: current_user)

			redirect_to question

		elsif params[:answer_id].present?

			answer = Answer.find(params[:answer_id])
			answer.votes.create(user: current_user)

			redirect_to answer.question

		end

	end

	def destroy

		if params[:question_id].present?

			question = Question.find(params[:question_id])
			question.votes.where(user: current_user).take.try(:destroy)

			redirect_to question

		elsif params[:answer_id].present?

			answer = Answer.find(params[:answer_id])
			answer.votes.where(user: current_user).take.try(:destroy)

			redirect_to answer.question

		end

	end		

end

app/helpers/application_helper.rb
module ApplicationHelper

	def markdown(text)

		options = {
			filter_html: true,
			hard_wrap: true,
			link_attributes: { rel: 'nofollow', target: '_blank' },
			space_after_header: true,
			fenced_code_blocks: true
		}
		
		extensions = {
			autolink: true,
			superscript: true,
			disable_indented_code_blocks: true
		}

		renderer = Redcarpet::Render::HTML.new(options)
		markdown = Redcarpet::Markdown.new(renderer, extensions)

		markdown.render(text).html_safe

	end

end

app/helpers/questions_helper.rb
module QuestionsHelper

	def form_title
		@question.new_record? ? "Ask Question" : "Edit Question"
	end

end

app/views/answers/_form.html.erb
<div class="row">
	<div class="col">
		<%= form_for [@question, @question.answers.build] do |f| %>
		<div class="form-group">
		  <%= f.text_area :body, class: "form-control", placeholder: "Add Answer" %>
		</div>

		<div class="actions text-right">
		  <%= f.submit "Answer", class: "btn btn-primary font-weight-bold" %>
		</div>
		<% end %>

	</div>
</div>

app/views/answers/_show.html.erb
<div class="row">
  <div class="col">
    <% @question.answers.each do |answer| %>
      
        <div class="card">
          <div class="card-header"><img style="width: 30px;" src="<%= Gravatar.new("#{answer.user.email}").image_url %>" class="rounded-circle" />
            <small><%= answer.user.email %>, 
              <strong><%= time_ago_in_words(answer.created_at) %> ago.</strong>
            </small>
          </div>
          <div class="card-body">
            <%= markdown(answer.body) %> 
          </div>
        </div>
        <hr>

        <div class="votes text-center">
          <% if answer.voted_by? current_user %>
            Votes: <%= answer.votes.count %> |
            <%= link_to 'Unvote Answer',answer_vote_path(answer), method: :delete %>
          <% else %>
            Votes: <%= answer.votes.count %> |
            <%= link_to 'Upvote Answer', answer_vote_path(answer), method: :post%>
          <% end %>
        </div>

        <hr>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <% answer.comments.each do |comment| %>
        <div class="card">
          <div class="card-header answer-header"><img style="width: 15px;" src="<%= Gravatar.new("#{answer.user.email}").image_url %>" class="rounded-circle" />
            <small><%= answer.user.email %>, 
              <strong><%= time_ago_in_words(answer.created_at) %> ago.</strong>
            </small>
          </div>
          <div class="card-body"> <%= markdown(comment.body) %></div>
        </div>
      <% end %>
      
      <div class="container">
        <% if signed_in? %>
          <%= form_for [answer, answer.comments.build] do |f| %>
            <div class="form-group">
              <%= f.text_area :body, class: "form-control my-4", placeholder: "Add Comment"%>
            </div>
            <%= f.submit "Comment", class: "btn btn-primary font-weight-bold float-right" %>
          <% end %>
        <% end %>  
      </div>
    <% end %>
    </div>
  </div>  
<hr>
</div>    

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">  
  <div class="container">
    <a class="navbar-brand" href="/">Flow<span class="light">Overstack</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mx-2">        
        <form class="form-inline my-2 my-lg-0">
          <%= form_tag questions_path, method: :get do %>
            <div class="form-group">
              <%= text_field_tag :title, params[:title], class: "form-control", placeholder: "Search" %>
            </div>
          <% end %>
        </form>

      <% if signed_in? %>
        <li class="nav-item dropdown mr-2">
          <a class="nav-item nav-link dropdown-toggle mr-md-2 avatar" href="#" id="bd-versions" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="<%= Gravatar.new("#{current_user.email}").image_url %>" class="rounded-circle" />
            <span class="caret"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:"dropdown-item" %>
          </div>
        </li>
        <li class="nav-item mr-2 my-auto"><%= link_to "<span class='fas fa-plus-circle'></span>".html_safe, new_question_path %></li>

      <% else %>
        <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "Log In", new_user_session_path, class: 'nav-link' %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Flow Overstack</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    
    <div class="container <%= controller_name %> <%= action_name %>">

      <div class="container">
        <% if flash.any? %>
          <% flash.keys.each do |key| %>
            <div class="alert alert-<%= key.to_s %> my-3" role="alert" style="background-color: rgb(204, 229, 255)">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <%= flash[key] %>
            </div>
          <% end %>
        <% end %>
      </div>
  
      <div class="col">
        <%= yield %>
      </div>

    </div>

  </body>
</html>

app/views/questions/_form.html.erb
<% provide(:page_title, "New Question") %>

<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-3 my-5">

      <h2 class="text-center mb-4"><%= form_title %></h2>
      
      <% if @question.errors.any? %>
        <div class="alert alert-danger">
          <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for @question do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control input-lg", placeholder: "Title" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, class: "form-control input-lg", placeholder: "Description" %>
        </div>
        <div>
          <%= f.submit form_title, class: "btn btn-primary btn-sm btn-block font-weight-bold" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<% provide(:page_title, 'Home') %>

<div class="container">
  <div class="row my-5">

    <div class="col-sm-6 offset-sm-3">
      
      <% @questions.each do |question| %>

        <div class="float-right">

          <i class="fas fa-comments"></i>
          <%= question.answers.count %>         
          
          <br>

          <i class="fas fa-caret-up mr-2"></i>
          <%= question.votes.count %>
        </div>

        <h3 class="my-0"><%= link_to question.title, question %></h3>
        <small>Asked by <%= question.user.email %>, <%= time_ago_in_words(question.created_at) %> ago.</small>
        <p class="my-0"><%= markdown(truncate(question.description, :length => 250)) %></p>

        <hr>

      <% end %>

    </div>

  </div>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<% provide(:page_title, @question.title) %>

<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <div class="question">
        <h2><%= @question.title %></h2>
        <small>Asked by <%= @question.user.email %>, <%= time_ago_in_words(@question.created_at) %> ago.</small>
        <div class="signed_in">
          <% if signed_in? && @question.user == current_user %>
              
            <%= link_to "<i class='fas fa-pen'></i>".html_safe, edit_question_path(@question) %>
            <%= link_to "<i class='fas fa-trash'></i>".html_safe, @question, method: :delete, data: { confirm: "Are you sure?" } %>
              
          <% end %>
        </div>
        <p><%= markdown(@question.description) %></p>
        <hr>
        <div class="votes">
          <% if @question.voted_by? current_user %>
            Votes: <%= @question.votes.count %> |
            <%= link_to 'Unvote Question',question_vote_path(@question), method: :delete %>
          <% else %>
            Votes: <%= @question.votes.count %> |
            <%= link_to 'Upvote Question', question_vote_path(@question), method: :post %>
          <% end %>
        </div>

        <hr>
      </div>  

    </div>
  </div>

  <div class="row">
    <h4><strong>Comments</strong></h4>
  </div>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <% @question.comments.each do |comment| %> 
        <div class="card mb-4">
          <div class="card-header">
            <img style="width: 20px;" src="<%= Gravatar.new("#{comment.user.email}").image_url %>" class="rounded-circle" />
            <small><%= comment.user.email %>, 
              <strong><%= time_ago_in_words(comment.created_at) %> ago.</strong>
            </small>
          </div>
          <div class="card-body"> <%= markdown(comment.body) %> </div>
        </div>
      <% end %>

      <% if signed_in? %>
        <%= form_for [@question, @question.comments.build] do |f| %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "Add Comment"%>
          </div>
            <%= f.submit "Comment", class: "btn btn-primary float-right font-weight-bold" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <hr>

  <div class="row">
    <h4><strong>Answers</strong></h4>
  </div>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <%= render 'answers/show' %>

      <% if signed_in? %>
        <%= render 'answers/form' %>
      <% end %>
    </div>
  </div>

  <hr>

</div>